### ISSUE TITLE
Audit Logs JSON API: 403 when using an organization access token.

### ISSUE THREAD

**Issue by alexstojda** [pulumi/service-requests#131]
### What happened?

I'm trying to export [Audit Logs (JSON)](https://www.pulumi.com/docs/reference/service-rest-api/#get-audit-log-events-json) via the API using an organization token.

According to the docs, an organization token [should have permission](https://www.pulumi.com/docs/intro/pulumi-service/organization-access-tokens/#audit-logs) to perform that operation, but i'm getting `{"code":403,"message":"You do not have permission to perform this operation."}`
<img width="416" alt="image" src="https://user-images.githubusercontent.com/1353716/200706791-02218aca-d7ba-4cd2-a0ec-f60381ba8620.png">

The endpoint works for the same organization when using a personal access token.

We are on the Enterprise plan as well. 

### Steps to reproduce

1. Create organization access token 
2. Make a GET call to `https://api.pulumi.com/api/orgs/{org}/auditlogs`

### Expected Behavior

Endpoint should return the audit log events

### Actual Behavior

API Returns a 403 when using an organization access token. 

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by djgrove** [comment]
Hi @alexstojda. Thanks for taking the time to bring this to our attention. This is an error in our documentation, apologies for this. Above the `API Access` section we have a contradiction:

> Organization Access Tokens behave like an organization member with stack write permissions to all of the organization’s stacks.

This is correct. The Audit Logs endpoints are admin-access only, and thus org tokens do not have access to list or export audit logs endpoints. At the time of launch, we opted to keep these tokens as restrictive as possible with the potential to make them more flexible over time as we receive feedback, since it's difficult to walk back any privileges to organization and team tokens once we've granted them.

I'll get these docs fixed and published. In the meantime I will open a feature request that yourself and others can chime in and upvote.

**Comment by djgrove** [comment]
OK. I've opened a [pull request](https://github.com/pulumi/pulumi-hugo/pull/2201) to fix our docs, and a [feature request](https://github.com/pulumi/service-requests/issues/135) based on your needs here for org tokens to programmatically access audit logs. Links included for redundancy. When the docs PR goes in I am going to close this ticket, but please feel free to leave any other feedback on the feature request.
