### ISSUE TITLE
Implement a pulumi provider for the pulumi service

### ISSUE THREAD

**Issue by filip-zyzniewski** [pulumi/service-requests#18]
It would be nice if the setup at https://app.pulumi.com/ could be managed with code.
It's a bit funny that a service that is all about configuration as code can't be configured with code (unless I missed the way to do that).

## Affected feature

The Pulumi service.

**Comment by MitchellGerdisch** [comment]
Although I would expect the provider to be comprehensive for the service, I wanted to capture some specific use-cases to make sure they are supported:
- The provider should support managing stack tags.
- The provider should support team-stack permissions assignment management
- Policy as code should be able to work with the provider so that I can write policies that, say, ensure stack tags are set correctly.

**Comment by cnunciato** [comment]
For those who happen to land here looking for docs for the Pulumi Service REST API (which this provider would wrap), you'll find them here: https://www.pulumi.com/docs/reference/service-rest-api/

**Comment by mchaynes** [comment]
We've released the pulumi service provider!

You can check it out at: https://github.com/pulumi/pulumi-pulumiservice

If you'd like to read more about it, check out the blog post we published as part of the PulumiUP event: https://www.pulumi.com/blog/announcing-pulumi-service-provider/

Please add an issue to the provider's repo if you would like to request features or file bugs.

PS: I've gone ahead and added an issue to add team-stack permissions to the new repo: https://github.com/pulumi/pulumi-pulumiservice/issues/51
