### ISSUE TITLE
Pulumi console doesn't show diff details

### ISSUE THREAD

**Issue by piotr-bzdyl-vertexinc** [pulumi/service-requests#34]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

`pulumi preview` shows the following (edited to the specific change and masked sensitive data):

```
~   ├─ github:index:Repository           some-github-repo    update      [diff: ~archived]
```

`pulumi preview --diff` also works fine:

```
    ~ github:index/repository:Repository: (update)
        [id=some-github-repo]
        [urn=urn:pulumi:prod::**masked**::github:index/repository:Repository::some-github-repo]
        [provider=urn:pulumi:prod::**masked**::pulumi:providers:github::default_4_9_0::fc692e00-ec67-4ec5-977e-4603e71a3f33]
      ~ archived: false => true
```

But the Pulumi console doesn't show `archived` attribute change in the diff:

```
some-github-repo (github:index:Repository)
~  github:index/repository:Repository (update)
    [id=some-github-repo]
    [urn=urn:pulumi:prod::**masked**::github:index/repository:Repository::some-github-repo]
    id                 : "some-github-repo"
```

![Screenshot 2022-01-05 at 08 34 05](https://user-images.githubusercontent.com/94372431/148178362-2c672692-9b05-4e75-bd61-5b52180f0716.png)

**Comment by komalali** [comment]
Hmm I'm not sure if this was fixed since this issue was created, but I can see the diff of what has changed when I click on the `diff` tab.

Examples:
<img width="1392" alt="Screen Shot 2022-08-29 at 4 26 34 PM" src="https://user-images.githubusercontent.com/24326455/187302204-8db716bf-5455-49fd-8b02-d0825d45a11d.png">
<img width="1185" alt="Screen Shot 2022-08-29 at 4 28 41 PM" src="https://user-images.githubusercontent.com/24326455/187302433-2ea436df-7409-4819-b48a-2cd9302995a7.png">
<img width="1197" alt="Screen Shot 2022-08-29 at 4 30 37 PM" src="https://user-images.githubusercontent.com/24326455/187302700-3b8bb734-274e-495f-9a2c-5b82817e276c.png">


Gonna close this out as it appears this is resolved, feel free to reopen if there are any outstanding issues here.

**Comment by EvanBoyle** [comment]
While you can see it in the console, it doesn't render in the default view the way the CLI does. The first snippet @piotr-bzdyl-vertexinc shows:
```
~   ├─ github:index:Repository           some-github-repo    update      [diff: ~archived]
```
The CLI shows `[diff:...` inline without having to `--diff`. The diff tab in the console seems equivalent to `--diff`
However, seems reasonable that users might want to see the diff summary inline in the default view like they do in the console.

Going to reopen this issue to track that request.
