### ISSUE TITLE
Long operation messages are truncated in the service

### ISSUE THREAD

**Issue by clstokes** [pulumi/service-requests#41]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

If a user uses the `-m` argument to pass in a custom message for their operation, the message is truncated when displayed in the Pulumi Service and there does not seem to be a way to see the full message. This occurs with multi-line messages too.

![screenshot-2022-02-02-17-16-58@2x](https://user-images.githubusercontent.com/293763/152265096-a60e064d-db94-42c1-ac0c-824bc323d23a.png)

### Steps to reproduce

1. `pulumi new typescript -y`
2. `pulumi up -m "This is the song that never ends, It just goes 'round and 'round, my friends, Some people started singing it, Not knowing what it was, And we continue singing it forever just because"`
3. `pulumi console` to view the message in the service

Expected: Should be able to see the full message.
Actual: Only see a truncated message

**Comment by susanev** [comment]
the user experience team can take on fixing this, will add it to our board

**Comment by anita-trimbur** [comment]
## [Figma File](https://www.figma.com/file/YDccwH65TZqBu92oL1xcWy/Expand-Operation-Messages?node-id=0%3A1)

## Design Changes

- Add expander to Update cards in instances where the operation message would otherwise be cut-off
- Switch the position of the operation message and the update status to allow the card to expand its body rather than its header
- Shift the diff indicator upward and in line with the header so that the expand icon can take its position in line with the body
- Ideally, these changes should not only affect the Details view, but also the Activity Feed (if eng time permits). The only additional changes here would be to make the "Details" link more prominent to ensure it is visually separated from the now-adjacent operation message

![Group 1](https://user-images.githubusercontent.com/97129308/152599042-38a40ce4-c43a-47bb-a9bc-d4d628832ded.png)
![Expanded](https://user-images.githubusercontent.com/97129308/152599047-a229e124-1088-4e40-ad31-97a1bf693456.png)

## Additional Notes

- After meeting with Kimberley, it is likely not ideal to use the Material Angular expander component considering the eng time necessary to make modifications to its pre-existing functionality
- If a user is specifically looking to expand the operation message from the Activity or Stack tab, they will first have to click "Details," then click the expander on the following page. This additional step appears to be necessary considering that if we were to expand the operation message by default on the Details page, it could push down other critical information users may be trying to access (Changes, Timeline, Config, etc). We cannot assume that by clicking Details the majority of users want the full description exposed. We may be able to revisit this in the future if we want to take a more involved approach to optimizing this flow.
