### ISSUE TITLE
Show count of matching resources when filtered

### ISSUE THREAD

**Issue by kimberleyamackenzie** [pulumi/service-requests#84]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
From a user via the console's feedback dialog:

Feature request: when I filter the list of resources, please show a count of the resources that match the filter and are displayed. Thank you.

## Adjustments
* use badges with rounded corners instead of circles to accommodate 3-digit numbers
* removed filter tags for scope
* adjusted badge contrast for accessibility
* added badge in dropdown for "all resources"
* added total count of resources on screen to the top left of the table
* removed "0" count badges

### Dropdown with resource count badges
<img width="245" alt="complex dropdown" src="https://user-images.githubusercontent.com/97129308/191097210-3c300248-c32c-4bef-a8f3-51d8695484d6.png">

### Screens

<img width="1512" alt="all (2)" src="https://user-images.githubusercontent.com/97129308/191104662-2882e86d-e9ce-4e41-b267-da61cde4678b.png">

<img width="1512" alt="filtered (2)" src="https://user-images.githubusercontent.com/97129308/191104654-d4b86203-44bc-4690-8ea6-e8aa64e958b9.png">

**Comment by susanev** [comment]
@jonelleb can you do the ux design work for this next week?

**Comment by jonelleb** [comment]
Sure, no problem.

**Comment by jonelleb** [comment]
# [Figma File](https://www.figma.com/file/2y2xkS3XrGT2NCd1nP5ZnR/Resource-Filtering?node-id=0%3A1)
# [Figma Prototype](https://www.figma.com/proto/2y2xkS3XrGT2NCd1nP5ZnR/Resource-Filtering?page-id=0%3A1&node-id=1%3A297&viewport=1627%2C3062%2C1&scaling=scale-down-width&starting-point-node-id=1%3A297)

# Design Changes / Engineer Notes
- Adding new filter result component to Stacks-Resources page: filter icon, name and count, with close icon 

![Screen Shot 2022-08-22 at 3 22 25 PM](https://user-images.githubusercontent.com/100616532/186014691-81b9f8a5-7441-489c-9628-095eb7e4311b.png)

**Comment by susanev** [comment]
@jonelleb is there anyway we can locate this closer to the search/filter? or in its own area somewhere? i don't think its working very well to have this in the same area as the list/graph toggle as these things are unrelated.

**Comment by jonelleb** [comment]
> @jonelleb is there anyway we can locate this closer to the search/filter? or in its own area somewhere? i don't think its working very well to have this in the same area as the list/graph toggle as these things are unrelated.
> 
> i also think we should consider showing the counts in the type dropdown, and keeping this applied filter for the search results. or at least we should consider various combinations of using the type dropdown and search together.

I've updated the design, please check it out and let me know if this works. Thanks!

**Comment by susanev** [comment]
@jonelleb this is headed in a better direction; but lets zoom about this next week

**Comment by susanev** [comment]
@jonelleb thanks for updating this, but we are still missing the total count of resources that are visible after applying a filter. this is the most important problem to solve. people want to know the count of resources on this page, both before and after a filter is applied. since i know your heading off on pto, would you mind if @anita-trimbur picked up the rest of this work next week?

**Comment by jonelleb** [comment]
Sure, that's fine. Thanks.

**Comment by susanev** [comment]
@anita-trimbur one other thing on this, i think it could be common that a bunch of these are 0's in that. menu, so i think we may want to show no badge at all in that case, so we dont present the user with a giant list of zeros.

**Comment by anita-trimbur** [comment]
@susanev let me know if these changes address your goals or if i need to realign!

## [Figma file](https://www.figma.com/file/2y2xkS3XrGT2NCd1nP5ZnR/Resource-Filtering?node-id=0%3A1)

## Adjustments
* use badges with rounded corners instead of circles to accommodate 3-digit numbers
* removed filter tags for scope
* adjusted badge contrast for accessibility
* added badge in dropdown for "all resources"
* added badge to "Resources" header, reflects total count of resources on screen when filters are adjusted (same design pattern used in our Registry)
* removed "0" count badges

### Dropdown with resource count badges
<img width="245" alt="complex dropdown" src="https://user-images.githubusercontent.com/97129308/191097210-3c300248-c32c-4bef-a8f3-51d8695484d6.png">

### Screens

<img width="1512" alt="all" src="https://user-images.githubusercontent.com/97129308/191095492-464b7ae4-4c40-4ec5-91f2-7bbc813a7498.png">

<img width="1512" alt="filtered" src="https://user-images.githubusercontent.com/97129308/191095495-2ee277c4-5291-4437-ae3c-a0b706441fc9.png">

**Comment by susanev** [comment]
@anita-trimbur love the dropdown updates!! what would you think of putting the count directly above the table on the right instead of as part of the heading. i think this may make it easier for folks to see when it changes when they apply the filter. and am worried it might get lost if we place it above the list/graph toggle.

**Comment by anita-trimbur** [comment]
for sure, i can show what that would look like! we could consider showing the badge in the collapsed state of the dropdown as well

**Comment by anita-trimbur** [comment]
@susanev this is what it could look like with your suggested positioning. i like that this preserves the little cloud icon and count combo that we use across the service to communicate resource count.

<img width="1512" alt="filter showing" src="https://user-images.githubusercontent.com/97129308/191101161-6515af67-ad4a-4be5-bf72-5e2730a37665.png">

also showing what it would look like if we included the badge in the collapsed state of the dropdown. this would ensure the change is happening exactly in the location the user is taking action.

<img width="1512" alt="filter collapse" src="https://user-images.githubusercontent.com/97129308/191101617-5a9241ca-9249-4044-b48b-75583ca9bd36.png">

**Comment by susanev** [comment]
@anita-trimbur we should maybe zoom, cause Jonelle got hung up on this too,  but the search can also change the count, so we need it outside of that menu, or at least we need a total count on the table too. last lil' nit is to have the text label be `Resources:` instead of `Showing`. otherwise, this is good to go from my perspective.

**Comment by susanev** [comment]
@sean1588 we were hoping 🤞🏻 that youd be up for picking this up. what do you think?

**Comment by anita-trimbur** [comment]
ah gotcha! cool, i can change the text label and update the screenshots in this issue

**Comment by susanev** [comment]
@anita-trimbur one other thing. so there was a lot of discussion on this issue. can you move the links to your designs as well as a text description of this work up into the issue description?
